# Dependencies
permalink: /:year/:month/:title.html
markdown: kramdown
highlighter: rouge

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            Dont
tagline:          "Dont's blog"
description:      '前端攻城尸'
url:              http://hyde.getpoole.com
baseurl:          /githublog
homelink: http://shellphon.wang

exclude: [node_modules, gulpfile.js, README.md, tmp, dev]

#paginate:         5

gems:
   - jekyll-paginate
   - jekyll-gist